### ISSUE TITLE
[integration] Blockfolio Signal

### ISSUE THREAD

**Issue by bitcoinsfacil** [bitshares/marketing#36]
Contacted them and here are the answers:
```It looks like we on boarded Bitshares to the Blockfolio Signal platform back in November of 2018, but no one from your team ever logged in or made a post.```

```We currently only have one team member listed for the Bitshares team and they have not logged in or responded to any emails to get them started. Do you have updated contact information for the bitshares team that you would like to provide in order to get them started posting?```

The team member is @ryanRfox I could put myself there if needed to streamline the news into Signal

**Comment by ryanRfox** [comment]
I support the use of signal for the BitShares project. However, before we begin using it, the Marketing Team must establish a plan for its use (what do we want to say, to whom and how often) and identify who will have access to "push the button" for posting. 

Let's use this Issue to establish a task list (suggest to add it to the OP description so it is easy to find and update). Rough outline:

### Task List
- [ ] Ready for first Signal Post
  - [ ] Define Authorized Posters
    - [ ] Identify Team(s) Representative 
    - [ ] Identify DAC Representative(s)
  - [ ] Define Posting Criteria
    - [ ] What must the message contain (and not) 
    - [ ] Frequency
  - [ ] Provide Example Posts
    - [ ] Core Protocol Release
    - [ ] Mobile Wallet Feature Release
    - [ ] DAC Sponsorship of Decentralized
    - [ ] Other
  - [ ] Other...

**Comment by bitcoinsfacil** [comment]
Who is the marketing team @ryanRfox ?

**Comment by ryanRfox** [comment]
Presently, I'd say those contributing within the repo. It would be better to have a DAC approved worker proposal with some clarifying details. At this time, none exist.

**Comment by bitcoinsfacil** [comment]
Marketing issues will pill up endlessly without it @ryanRfox and with the current situation on voting, we might not move. 
I believe in clear communication as a way of reinforcing what the workers are doing and have done. With a clear business, one-sheet marketing can do miracles. It needs some freedom to sail until finding the ideal message needed `now`. 

To answer your questions: 

1) what do we want to say> We are alive since 2014 
2) to whom> To those who ask
3) how often> As much as we can

**Comment by sschiessl-bcp** [comment]
A simply first step is to integrate news.bitshares.org to stream into Blockfolio. Thoughts?
